"""Agent adapter contracts for CadFlow."""

from ai_native_cad.agents.base import AgentAdapter
from ai_native_cad.agents.deterministic import DeterministicAgentAdapter
from ai_native_cad.agents.design_planner_fake import DesignPlannerFakeAgentAdapter
from ai_native_cad.agents.json_contract import (
    JsonContractAgentAdapter,
    JsonContractClient,
    JsonContractProviderConfig,
    JsonContractProviderError,
)
from ai_native_cad.agents.provider_clients import (
    JsonProviderEndpoint,
    OpenAICompatibleJsonContractClient,
    OpenAIResponsesJsonContractClient,
    make_json_contract_adapter_from_env,
)
from ai_native_cad.agents.validation import validate_adapter_result
from ai_native_cad.agents.episode import (
    ALLOWLISTED_ACTIONS,
    CONTEXT_KEYS,
    AgentAction,
    AgentCapabilities,
    AgentEpisodeResult,
    AgentObjective,
    ContextBroker,
    ContextEnvelope,
    EpisodeBudget,
    EpisodeOrchestrator,
    StopReason,
    build_create_part_ir_context,
    build_design_part_context,
    run_create_part_ir_episode,
    run_design_part_episode,
)
from ai_native_cad.agents.registry import (
    DESIGN_PART_SKILL,
    RUNTIME_KNOWLEDGE,
    RUNTIME_SKILL_REGISTRY,
    BudgetDefinition,
    KnowledgeDefinition,
    SkillDefinition,
    SkillRegistry,
)
from ai_native_cad.agents.tool_broker import (
    MODEL_PROGRAM_SOURCE_TOOL,
    MODEL_PROGRAM_TOOL,
    REQUIRED_MODEL_PROGRAM_CONTROLS,
    STRUCTURED_CONTRACT_TOOL,
    CadFlowToolBroker,
    ModelProgramExecutionRequest,
    SandboxAttestation,
    SandboxCapability,
    ToolInvocationContext,
    ToolDefinition,
    ToolObservation,
    detect_model_program_sandbox_capability,
)
from ai_native_cad.agents.model_program_policy import (
    CADQUERY_MODEL_PROGRAM_API,
    CADQUERY_MODEL_PROGRAM_ENTRYPOINT,
    cadquery_model_program_policy_manifest,
    validate_cadquery_model_program_source,
)

__all__ = [
    "AgentAdapter",
    "AgentAction",
    "AgentCapabilities",
    "AgentEpisodeResult",
    "AgentObjective",
    "ALLOWLISTED_ACTIONS",
    "CONTEXT_KEYS",
    "ContextBroker",
    "ContextEnvelope",
    "CadFlowToolBroker",
    "DESIGN_PART_SKILL",
    "DesignPlannerFakeAgentAdapter",
    "DeterministicAgentAdapter",
    "EpisodeBudget",
    "EpisodeOrchestrator",
    "BudgetDefinition",
    "JsonContractAgentAdapter",
    "JsonContractClient",
    "JsonContractProviderConfig",
    "JsonContractProviderError",
    "JsonProviderEndpoint",
    "KnowledgeDefinition",
    "CADQUERY_MODEL_PROGRAM_API",
    "CADQUERY_MODEL_PROGRAM_ENTRYPOINT",
    "MODEL_PROGRAM_SOURCE_TOOL",
    "MODEL_PROGRAM_TOOL",
    "ModelProgramExecutionRequest",
    "OpenAICompatibleJsonContractClient",
    "OpenAIResponsesJsonContractClient",
    "StopReason",
    "RUNTIME_SKILL_REGISTRY",
    "RUNTIME_KNOWLEDGE",
    "REQUIRED_MODEL_PROGRAM_CONTROLS",
    "STRUCTURED_CONTRACT_TOOL",
    "SandboxCapability",
    "SandboxAttestation",
    "SkillDefinition",
    "SkillRegistry",
    "ToolDefinition",
    "ToolInvocationContext",
    "ToolObservation",
    "build_create_part_ir_context",
    "build_design_part_context",
    "cadquery_model_program_policy_manifest",
    "detect_model_program_sandbox_capability",
    "make_json_contract_adapter_from_env",
    "run_create_part_ir_episode",
    "run_design_part_episode",
    "validate_adapter_result",
    "validate_cadquery_model_program_source",
]
